### PR TITLE
ActiveRecord#serialize compatibility: Add load and dump, with to_i

### PR DESCRIPTION
**Pull request by pboling**
Adds:
* `Month.load`
* `Month.dump`
* `Month#to_i`
* specs for each

### CODE REVIEW

**Comment by timcraft** [comment]
@pboling You're correct that there's an incompatibility but the root issue is a bug in the <=> operator, so no need to define custom dump/load methods. Fixed in e022c0d (available in v1.4.0)

Thanks for the heads up!

**Comment by pboling** [comment]
@timcraft would you consider adding just the `to_i` method?  You are already using that exact logic in the gem, you just hadn't named it.  I need to make extensive use of `to_i`.

**Comment by timcraft** [comment]
@pboling I can't see a good reason to add to_i: there isn't a "standard" definition for month numbering (unlike e.g. unix time or ISO week numbering), Date doesn't have to_i, and months aren't numerics (to_f makes no sense either). The logic already exists but that's an internal implementation detail (it could be implemented differently). If it's important to your application I'd suggest defining it in your application, whether you prefer to monkey patch Month or define it otherwise is up to you.

**Comment by pboling** [comment]
I actually need it across a set of disparate tools, so I want to have a single monkey patch that I can share widely, so I will probably release the enhancement as a gem plugin, that extends this gem.  Perhaps I'll call it `month-extentions`.

**Pull request closed without merging**
